manager:
  entity:
    limit-world: 2500
    limit-chunk: 16
    spawner:
      chance: 30
    control:
      sheep:
        lifetime: 0
  spigot:
    view-distance: 4
    entity-activation: 4
    tab-complete: false
