manager:
  chunk:
    auto-unload: true
    limit-total: 6500
    purge-on-unload:
  redstone:
    limit-freq: 35
    white-list:
    - 63
    - 68
    replace: false
  player:
    limit-addr: 2
    white-list:
    - '127.0.0.1'
  entity:
    limit-world: 2500
    limit-chunk: 16
    spawner:
      chance: 30
    control:
      sheep:
        lifetime: 0
  spigot:
    view-distance: 4
    entity-activation: 4
    tab-complete: false
  restart:
    daily: 24
    limit: 5
